wandb_version: 1

task:
  desc: null
  value: classify
mode:
  desc: null
  value: train
model:
  desc: null
  value: yolov8n-cls.pt
data:
  desc: null
  value: /mnt/d/dacon/open/
epochs:
  desc: null
  value: 100
time:
  desc: null
  value: null
patience:
  desc: null
  value: 100
batch:
  desc: null
  value: 16
imgsz:
  desc: null
  value: 224
save:
  desc: null
  value: true
save_period:
  desc: null
  value: -1
cache:
  desc: null
  value: false
device:
  desc: null
  value: null
workers:
  desc: null
  value: 0
project:
  desc: null
  value: null
name:
  desc: null
  value: train
exist_ok:
  desc: null
  value: false
pretrained:
  desc: null
  value: true
optimizer:
  desc: null
  value: auto
verbose:
  desc: null
  value: true
seed:
  desc: null
  value: 0
deterministic:
  desc: null
  value: true
single_cls:
  desc: null
  value: false
rect:
  desc: null
  value: false
cos_lr:
  desc: null
  value: false
close_mosaic:
  desc: null
  value: 10
resume:
  desc: null
  value: false
amp:
  desc: null
  value: true
fraction:
  desc: null
  value: 1.0
profile:
  desc: null
  value: false
freeze:
  desc: null
  value: null
multi_scale:
  desc: null
  value: false
overlap_mask:
  desc: null
  value: true
mask_ratio:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.0
val:
  desc: null
  value: true
split:
  desc: null
  value: val
save_json:
  desc: null
  value: false
save_hybrid:
  desc: null
  value: false
conf:
  desc: null
  value: null
iou:
  desc: null
  value: 0.7
max_det:
  desc: null
  value: 300
half:
  desc: null
  value: false
dnn:
  desc: null
  value: false
plots:
  desc: null
  value: true
source:
  desc: null
  value: null
vid_stride:
  desc: null
  value: 1
stream_buffer:
  desc: null
  value: false
visualize:
  desc: null
  value: false
augment:
  desc: null
  value: false
agnostic_nms:
  desc: null
  value: false
classes:
  desc: null
  value: null
retina_masks:
  desc: null
  value: false
embed:
  desc: null
  value: null
show:
  desc: null
  value: false
save_frames:
  desc: null
  value: false
save_txt:
  desc: null
  value: false
save_conf:
  desc: null
  value: false
save_crop:
  desc: null
  value: false
show_labels:
  desc: null
  value: true
show_conf:
  desc: null
  value: true
show_boxes:
  desc: null
  value: true
line_width:
  desc: null
  value: null
format:
  desc: null
  value: torchscript
keras:
  desc: null
  value: false
optimize:
  desc: null
  value: false
int8:
  desc: null
  value: false
dynamic:
  desc: null
  value: false
simplify:
  desc: null
  value: false
opset:
  desc: null
  value: null
workspace:
  desc: null
  value: 4
nms:
  desc: null
  value: false
lr0:
  desc: null
  value: 0.02145264726979644
lrf:
  desc: null
  value: 0.3207600729631463
momentum:
  desc: null
  value: 0.9606707030288459
weight_decay:
  desc: null
  value: 0.0008761410269040414
warmup_epochs:
  desc: null
  value: 0.09839789371762275
warmup_momentum:
  desc: null
  value: 0.6696432843664483
warmup_bias_lr:
  desc: null
  value: 0.1
box:
  desc: null
  value: 0.03874561038701885
cls:
  desc: null
  value: 2.9435643920838883
dfl:
  desc: null
  value: 1.5
pose:
  desc: null
  value: 12.0
kobj:
  desc: null
  value: 1.0
label_smoothing:
  desc: null
  value: 0.0
nbs:
  desc: null
  value: 64
hsv_h:
  desc: null
  value: 0.05079779778767705
hsv_s:
  desc: null
  value: 0.11771897675601968
hsv_v:
  desc: null
  value: 0.4939075838939244
degrees:
  desc: null
  value: 38.27639177338936
translate:
  desc: null
  value: 0.43830741863794465
scale:
  desc: null
  value: 0.7789964228213685
shear:
  desc: null
  value: 5.034365839735426
perspective:
  desc: null
  value: 0.0003950048889905633
flipud:
  desc: null
  value: 0.8293197276236547
fliplr:
  desc: null
  value: 0.6852105566938318
bgr:
  desc: null
  value: 0.554650744948261
mosaic:
  desc: null
  value: 0.756358531935498
mixup:
  desc: null
  value: 0.5720170500164166
copy_paste:
  desc: null
  value: 0.8383361984139049
auto_augment:
  desc: null
  value: randaugment
erasing:
  desc: null
  value: 0.4
crop_fraction:
  desc: null
  value: 1.0
cfg:
  desc: null
  value: null
tracker:
  desc: null
  value: botsort.yaml
save_dir:
  desc: null
  value: runs/classify/train
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714703377.0
    t:
      1:
      - 1
      - 11
      - 30
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 30
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
