wandb_version: 1

task:
  desc: null
  value: classify
mode:
  desc: null
  value: train
model:
  desc: null
  value: yolov8n-cls.pt
data:
  desc: null
  value: /mnt/d/dacon/open/
epochs:
  desc: null
  value: 100
time:
  desc: null
  value: null
patience:
  desc: null
  value: 100
batch:
  desc: null
  value: 32
imgsz:
  desc: null
  value: 224
save:
  desc: null
  value: true
save_period:
  desc: null
  value: -1
cache:
  desc: null
  value: false
device:
  desc: null
  value: null
workers:
  desc: null
  value: 0
project:
  desc: null
  value: null
name:
  desc: null
  value: train
exist_ok:
  desc: null
  value: false
pretrained:
  desc: null
  value: true
optimizer:
  desc: null
  value: auto
verbose:
  desc: null
  value: true
seed:
  desc: null
  value: 0
deterministic:
  desc: null
  value: true
single_cls:
  desc: null
  value: false
rect:
  desc: null
  value: false
cos_lr:
  desc: null
  value: false
close_mosaic:
  desc: null
  value: 10
resume:
  desc: null
  value: false
amp:
  desc: null
  value: true
fraction:
  desc: null
  value: 1.0
profile:
  desc: null
  value: false
freeze:
  desc: null
  value: null
multi_scale:
  desc: null
  value: false
overlap_mask:
  desc: null
  value: true
mask_ratio:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.0
val:
  desc: null
  value: true
split:
  desc: null
  value: val
save_json:
  desc: null
  value: false
save_hybrid:
  desc: null
  value: false
conf:
  desc: null
  value: null
iou:
  desc: null
  value: 0.7
max_det:
  desc: null
  value: 300
half:
  desc: null
  value: false
dnn:
  desc: null
  value: false
plots:
  desc: null
  value: true
source:
  desc: null
  value: null
vid_stride:
  desc: null
  value: 1
stream_buffer:
  desc: null
  value: false
visualize:
  desc: null
  value: false
augment:
  desc: null
  value: false
agnostic_nms:
  desc: null
  value: false
classes:
  desc: null
  value: null
retina_masks:
  desc: null
  value: false
embed:
  desc: null
  value: null
show:
  desc: null
  value: false
save_frames:
  desc: null
  value: false
save_txt:
  desc: null
  value: false
save_conf:
  desc: null
  value: false
save_crop:
  desc: null
  value: false
show_labels:
  desc: null
  value: true
show_conf:
  desc: null
  value: true
show_boxes:
  desc: null
  value: true
line_width:
  desc: null
  value: null
format:
  desc: null
  value: torchscript
keras:
  desc: null
  value: false
optimize:
  desc: null
  value: false
int8:
  desc: null
  value: false
dynamic:
  desc: null
  value: false
simplify:
  desc: null
  value: false
opset:
  desc: null
  value: null
workspace:
  desc: null
  value: 4
nms:
  desc: null
  value: false
lr0:
  desc: null
  value: 0.031589101598865736
lrf:
  desc: null
  value: 0.028844164674596377
momentum:
  desc: null
  value: 0.819523849916282
weight_decay:
  desc: null
  value: 0.00020621063803196883
warmup_epochs:
  desc: null
  value: 1.9728696932437806
warmup_momentum:
  desc: null
  value: 0.9157135371320021
warmup_bias_lr:
  desc: null
  value: 0.1
box:
  desc: null
  value: 0.13931458150180767
cls:
  desc: null
  value: 1.993923265105843
dfl:
  desc: null
  value: 1.5
pose:
  desc: null
  value: 12.0
kobj:
  desc: null
  value: 1.0
label_smoothing:
  desc: null
  value: 0.0
nbs:
  desc: null
  value: 64
hsv_h:
  desc: null
  value: 0.06750245031863301
hsv_s:
  desc: null
  value: 0.36983510096729594
hsv_v:
  desc: null
  value: 0.7468395003571588
degrees:
  desc: null
  value: 37.89228180845384
translate:
  desc: null
  value: 0.19900713277817683
scale:
  desc: null
  value: 0.8671904221371972
shear:
  desc: null
  value: 2.6079172147605734
perspective:
  desc: null
  value: 0.0005205396595902512
flipud:
  desc: null
  value: 0.036898574279843444
fliplr:
  desc: null
  value: 0.36736052858679247
bgr:
  desc: null
  value: 0.9208420520005404
mosaic:
  desc: null
  value: 0.869669990702922
mixup:
  desc: null
  value: 0.04921599692091616
copy_paste:
  desc: null
  value: 0.5417067742411378
auto_augment:
  desc: null
  value: randaugment
erasing:
  desc: null
  value: 0.4
crop_fraction:
  desc: null
  value: 1.0
cfg:
  desc: null
  value: null
tracker:
  desc: null
  value: botsort.yaml
save_dir:
  desc: null
  value: runs/classify/train
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714703644.0
    t:
      1:
      - 1
      - 11
      - 30
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 30
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      6: 4.32.1
      8:
      - 5
      13: linux-x86_64
